// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: tests/enum/enum_renames.proto

// clang-format off

package enum

import (
	_ "github.com/alta/protopatch/patch/gopb"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RenamedEnum int32

const (
	RenamedEnum_INVALID RenamedEnum = 0
	RenamedEnum_A       RenamedEnum = 1
	RenamedEnum_B       RenamedEnum = 2
	RenamedEnum_C       RenamedEnum = 3
)

// Enum value maps for OriginalEnum.
var (
	RenamedEnum_name = map[int32]string{
		0: "INVALID",
		1: "A",
		2: "B",
		3: "C",
	}
	RenamedEnum_value = map[string]int32{
		"INVALID": 0,
		"A":       1,
		"B":       2,
		"C":       3,
	}
)

func (x RenamedEnum) Enum() *RenamedEnum {
	p := new(RenamedEnum)
	*p = x
	return p
}

func (x RenamedEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RenamedEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_tests_enum_enum_renames_proto_enumTypes[0].Descriptor()
}

func (RenamedEnum) Type() protoreflect.EnumType {
	return &file_tests_enum_enum_renames_proto_enumTypes[0]
}

func (x RenamedEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OriginalEnum.Descriptor instead.
func (RenamedEnum) EnumDescriptor() ([]byte, []int) {
	return file_tests_enum_enum_renames_proto_rawDescGZIP(), []int{0}
}

type EnumWithRenamedValue int32

const (
	RenamedValue             EnumWithRenamedValue = 0
	EnumWithRenamedValue_ONE EnumWithRenamedValue = 1
)

// Enum value maps for EnumWithRenamedValue.
var (
	EnumWithRenamedValue_name = map[int32]string{
		0: "ORIGINAL_VALUE",
		1: "ONE",
	}
	EnumWithRenamedValue_value = map[string]int32{
		"ORIGINAL_VALUE": 0,
		"ONE":            1,
	}
)

func (x EnumWithRenamedValue) Enum() *EnumWithRenamedValue {
	p := new(EnumWithRenamedValue)
	*p = x
	return p
}

func (x EnumWithRenamedValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumWithRenamedValue) Descriptor() protoreflect.EnumDescriptor {
	return file_tests_enum_enum_renames_proto_enumTypes[1].Descriptor()
}

func (EnumWithRenamedValue) Type() protoreflect.EnumType {
	return &file_tests_enum_enum_renames_proto_enumTypes[1]
}

func (x EnumWithRenamedValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumWithRenamedValue.Descriptor instead.
func (EnumWithRenamedValue) EnumDescriptor() ([]byte, []int) {
	return file_tests_enum_enum_renames_proto_rawDescGZIP(), []int{1}
}

var File_tests_enum_enum_renames_proto protoreflect.FileDescriptor

var file_tests_enum_enum_renames_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75,
	0x6d, 0x5f, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x1a, 0x0e, 0x70, 0x61, 0x74,
	0x63, 0x68, 0x2f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x43, 0x0a, 0x0c, 0x4f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x49,
	0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x05, 0x0a, 0x01, 0x41, 0x10, 0x01, 0x12,
	0x05, 0x0a, 0x01, 0x42, 0x10, 0x02, 0x12, 0x05, 0x0a, 0x01, 0x43, 0x10, 0x03, 0x1a, 0x11, 0xca,
	0xb5, 0x03, 0x0d, 0x0a, 0x0b, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x45, 0x6e, 0x75, 0x6d,
	0x2a, 0x47, 0x0a, 0x14, 0x45, 0x6e, 0x75, 0x6d, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x4f, 0x52, 0x49, 0x47,
	0x49, 0x4e, 0x41, 0x4c, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x00, 0x1a, 0x12, 0xca, 0xb5,
	0x03, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x07, 0x0a, 0x03, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x70, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x65, 0x6e,
	0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tests_enum_enum_renames_proto_rawDescOnce sync.Once
	file_tests_enum_enum_renames_proto_rawDescData = file_tests_enum_enum_renames_proto_rawDesc
)

func file_tests_enum_enum_renames_proto_rawDescGZIP() []byte {
	file_tests_enum_enum_renames_proto_rawDescOnce.Do(func() {
		file_tests_enum_enum_renames_proto_rawDescData = protoimpl.X.CompressGZIP(file_tests_enum_enum_renames_proto_rawDescData)
	})
	return file_tests_enum_enum_renames_proto_rawDescData
}

var file_tests_enum_enum_renames_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tests_enum_enum_renames_proto_goTypes = []interface{}{
	(RenamedEnum)(0),          // 0: tests.enum.OriginalEnum
	(EnumWithRenamedValue)(0), // 1: tests.enum.EnumWithRenamedValue
}
var file_tests_enum_enum_renames_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tests_enum_enum_renames_proto_init() }
func file_tests_enum_enum_renames_proto_init() {
	if File_tests_enum_enum_renames_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tests_enum_enum_renames_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_enum_enum_renames_proto_goTypes,
		DependencyIndexes: file_tests_enum_enum_renames_proto_depIdxs,
		EnumInfos:         file_tests_enum_enum_renames_proto_enumTypes,
	}.Build()
	File_tests_enum_enum_renames_proto = out.File
	file_tests_enum_enum_renames_proto_rawDesc = nil
	file_tests_enum_enum_renames_proto_goTypes = nil
	file_tests_enum_enum_renames_proto_depIdxs = nil
}
