// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: tests/enum/enum_conformance.proto

// clang-format off

package enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_INVALID Kind = 0
	Kind_CHEAP   Kind = 1
	Kind_FAST    Kind = 2
	Kind_GOOD    Kind = 3
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "INVALID",
		1: "CHEAP",
		2: "FAST",
		3: "GOOD",
	}
	Kind_value = map[string]int32{
		"INVALID": 0,
		"CHEAP":   1,
		"FAST":    2,
		"GOOD":    3,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_tests_enum_enum_conformance_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_tests_enum_enum_conformance_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_tests_enum_enum_conformance_proto_rawDescGZIP(), []int{0}
}

type Outer_Route int32

const (
	Outer_INVALID Outer_Route = 0
	Outer_SLOW    Outer_Route = 1
	Outer_FAST    Outer_Route = 2
	Outer_SCENIC  Outer_Route = 3
)

// Enum value maps for Outer_Route.
var (
	Outer_Route_name = map[int32]string{
		0: "INVALID",
		1: "SLOW",
		2: "FAST",
		3: "SCENIC",
	}
	Outer_Route_value = map[string]int32{
		"INVALID": 0,
		"SLOW":    1,
		"FAST":    2,
		"SCENIC":  3,
	}
)

func (x Outer_Route) Enum() *Outer_Route {
	p := new(Outer_Route)
	*p = x
	return p
}

func (x Outer_Route) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outer_Route) Descriptor() protoreflect.EnumDescriptor {
	return file_tests_enum_enum_conformance_proto_enumTypes[1].Descriptor()
}

func (Outer_Route) Type() protoreflect.EnumType {
	return &file_tests_enum_enum_conformance_proto_enumTypes[1]
}

func (x Outer_Route) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outer_Route.Descriptor instead.
func (Outer_Route) EnumDescriptor() ([]byte, []int) {
	return file_tests_enum_enum_conformance_proto_rawDescGZIP(), []int{0, 0}
}

type Outer_Middle_Flavor int32

const (
	Outer_Middle_INVALID Outer_Middle_Flavor = 0
	Outer_Middle_SWEET   Outer_Middle_Flavor = 1
	Outer_Middle_SALTY   Outer_Middle_Flavor = 2
	Outer_Middle_SOUR    Outer_Middle_Flavor = 3
	Outer_Middle_BITTER  Outer_Middle_Flavor = 4
)

// Enum value maps for Outer_Middle_Flavor.
var (
	Outer_Middle_Flavor_name = map[int32]string{
		0: "INVALID",
		1: "SWEET",
		2: "SALTY",
		3: "SOUR",
		4: "BITTER",
	}
	Outer_Middle_Flavor_value = map[string]int32{
		"INVALID": 0,
		"SWEET":   1,
		"SALTY":   2,
		"SOUR":    3,
		"BITTER":  4,
	}
)

func (x Outer_Middle_Flavor) Enum() *Outer_Middle_Flavor {
	p := new(Outer_Middle_Flavor)
	*p = x
	return p
}

func (x Outer_Middle_Flavor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outer_Middle_Flavor) Descriptor() protoreflect.EnumDescriptor {
	return file_tests_enum_enum_conformance_proto_enumTypes[2].Descriptor()
}

func (Outer_Middle_Flavor) Type() protoreflect.EnumType {
	return &file_tests_enum_enum_conformance_proto_enumTypes[2]
}

func (x Outer_Middle_Flavor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outer_Middle_Flavor.Descriptor instead.
func (Outer_Middle_Flavor) EnumDescriptor() ([]byte, []int) {
	return file_tests_enum_enum_conformance_proto_rawDescGZIP(), []int{0, 0, 0}
}

type Outer_Middle_Inner_Arch int32

const (
	Outer_Middle_Inner_INVALID    Outer_Middle_Inner_Arch = 0
	Outer_Middle_Inner_ROMANESQUE Outer_Middle_Inner_Arch = 1
	Outer_Middle_Inner_GOTHIC     Outer_Middle_Inner_Arch = 2
	Outer_Middle_Inner_MODERN     Outer_Middle_Inner_Arch = 3
)

// Enum value maps for Outer_Middle_Inner_Arch.
var (
	Outer_Middle_Inner_Arch_name = map[int32]string{
		0: "INVALID",
		1: "ROMANESQUE",
		2: "GOTHIC",
		3: "MODERN",
	}
	Outer_Middle_Inner_Arch_value = map[string]int32{
		"INVALID":    0,
		"ROMANESQUE": 1,
		"GOTHIC":     2,
		"MODERN":     3,
	}
)

func (x Outer_Middle_Inner_Arch) Enum() *Outer_Middle_Inner_Arch {
	p := new(Outer_Middle_Inner_Arch)
	*p = x
	return p
}

func (x Outer_Middle_Inner_Arch) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outer_Middle_Inner_Arch) Descriptor() protoreflect.EnumDescriptor {
	return file_tests_enum_enum_conformance_proto_enumTypes[3].Descriptor()
}

func (Outer_Middle_Inner_Arch) Type() protoreflect.EnumType {
	return &file_tests_enum_enum_conformance_proto_enumTypes[3]
}

func (x Outer_Middle_Inner_Arch) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outer_Middle_Inner_Arch.Descriptor instead.
func (Outer_Middle_Inner_Arch) EnumDescriptor() ([]byte, []int) {
	return file_tests_enum_enum_conformance_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

type Outer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Outer) Reset() {
	*x = Outer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_enum_enum_conformance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer) ProtoMessage() {}

func (x *Outer) ProtoReflect() protoreflect.Message {
	mi := &file_tests_enum_enum_conformance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer.ProtoReflect.Descriptor instead.
func (*Outer) Descriptor() ([]byte, []int) {
	return file_tests_enum_enum_conformance_proto_rawDescGZIP(), []int{0}
}

type Outer_Middle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Outer_Middle) Reset() {
	*x = Outer_Middle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_enum_enum_conformance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outer_Middle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer_Middle) ProtoMessage() {}

func (x *Outer_Middle) ProtoReflect() protoreflect.Message {
	mi := &file_tests_enum_enum_conformance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer_Middle.ProtoReflect.Descriptor instead.
func (*Outer_Middle) Descriptor() ([]byte, []int) {
	return file_tests_enum_enum_conformance_proto_rawDescGZIP(), []int{0, 0}
}

type Outer_Middle_Inner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Outer_Middle_Inner) Reset() {
	*x = Outer_Middle_Inner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_enum_enum_conformance_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outer_Middle_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer_Middle_Inner) ProtoMessage() {}

func (x *Outer_Middle_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_tests_enum_enum_conformance_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer_Middle_Inner.ProtoReflect.Descriptor instead.
func (*Outer_Middle_Inner) Descriptor() ([]byte, []int) {
	return file_tests_enum_enum_conformance_proto_rawDescGZIP(), []int{0, 0, 0}
}

var File_tests_enum_enum_conformance_proto protoreflect.FileDescriptor

var file_tests_enum_enum_conformance_proto_rawDesc = []byte{
	0x0a, 0x21, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75,
	0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x22,
	0xd1, 0x01, 0x0a, 0x05, 0x4f, 0x75, 0x74, 0x65, 0x72, 0x1a, 0x91, 0x01, 0x0a, 0x06, 0x4d, 0x69,
	0x64, 0x64, 0x6c, 0x65, 0x1a, 0x44, 0x0a, 0x05, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x3b, 0x0a,
	0x04, 0x41, 0x72, 0x63, 0x68, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44,
	0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x4f, 0x4d, 0x41, 0x4e, 0x45, 0x53, 0x51, 0x55, 0x45,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x4f, 0x54, 0x48, 0x49, 0x43, 0x10, 0x02, 0x12, 0x0a,
	0x0a, 0x06, 0x4d, 0x4f, 0x44, 0x45, 0x52, 0x4e, 0x10, 0x03, 0x22, 0x41, 0x0a, 0x06, 0x46, 0x6c,
	0x61, 0x76, 0x6f, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x57, 0x45, 0x45, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x53, 0x41, 0x4c, 0x54, 0x59, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x4f, 0x55, 0x52, 0x10,
	0x03, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x49, 0x54, 0x54, 0x45, 0x52, 0x10, 0x04, 0x22, 0x34, 0x0a,
	0x05, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x4c, 0x4f, 0x57, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x46, 0x41, 0x53, 0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x43, 0x45, 0x4e, 0x49,
	0x43, 0x10, 0x03, 0x2a, 0x32, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x49,
	0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x48, 0x45, 0x41,
	0x50, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x53, 0x54, 0x10, 0x02, 0x12, 0x08, 0x0a,
	0x04, 0x47, 0x4f, 0x4f, 0x44, 0x10, 0x03, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x70, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x65, 0x6e, 0x75, 0x6d,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tests_enum_enum_conformance_proto_rawDescOnce sync.Once
	file_tests_enum_enum_conformance_proto_rawDescData = file_tests_enum_enum_conformance_proto_rawDesc
)

func file_tests_enum_enum_conformance_proto_rawDescGZIP() []byte {
	file_tests_enum_enum_conformance_proto_rawDescOnce.Do(func() {
		file_tests_enum_enum_conformance_proto_rawDescData = protoimpl.X.CompressGZIP(file_tests_enum_enum_conformance_proto_rawDescData)
	})
	return file_tests_enum_enum_conformance_proto_rawDescData
}

var file_tests_enum_enum_conformance_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_tests_enum_enum_conformance_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tests_enum_enum_conformance_proto_goTypes = []interface{}{
	(Kind)(0),                    // 0: tests.enum.Kind
	(Outer_Route)(0),             // 1: tests.enum.Outer.Route
	(Outer_Middle_Flavor)(0),     // 2: tests.enum.Outer.Middle.Flavor
	(Outer_Middle_Inner_Arch)(0), // 3: tests.enum.Outer.Middle.Inner.Arch
	(*Outer)(nil),                // 4: tests.enum.Outer
	(*Outer_Middle)(nil),         // 5: tests.enum.Outer.Middle
	(*Outer_Middle_Inner)(nil),   // 6: tests.enum.Outer.Middle.Inner
}
var file_tests_enum_enum_conformance_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tests_enum_enum_conformance_proto_init() }
func file_tests_enum_enum_conformance_proto_init() {
	if File_tests_enum_enum_conformance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tests_enum_enum_conformance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Outer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_enum_enum_conformance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Outer_Middle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_enum_enum_conformance_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Outer_Middle_Inner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tests_enum_enum_conformance_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_enum_enum_conformance_proto_goTypes,
		DependencyIndexes: file_tests_enum_enum_conformance_proto_depIdxs,
		EnumInfos:         file_tests_enum_enum_conformance_proto_enumTypes,
		MessageInfos:      file_tests_enum_enum_conformance_proto_msgTypes,
	}.Build()
	File_tests_enum_enum_conformance_proto = out.File
	file_tests_enum_enum_conformance_proto_rawDesc = nil
	file_tests_enum_enum_conformance_proto_goTypes = nil
	file_tests_enum_enum_conformance_proto_depIdxs = nil
}
