// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: tests/enum/nested.proto

// clang-format off

package enum

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Outer_Inner int32

const (
	Outer_INVALID Outer_Inner = 0
	Outer_A       Outer_Inner = 1
	Outer_B       Outer_Inner = 2
	Outer_C       Outer_Inner = 3
)

// Enum value maps for Outer_Inner.
var (
	Outer_Inner_name = map[int32]string{
		0: "INVALID",
		1: "A",
		2: "B",
		3: "C",
	}
	Outer_Inner_value = map[string]int32{
		"INVALID": 0,
		"A":       1,
		"B":       2,
		"C":       3,
	}
)

func (x Outer_Inner) Enum() *Outer_Inner {
	p := new(Outer_Inner)
	*p = x
	return p
}

func (x Outer_Inner) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outer_Inner) Descriptor() protoreflect.EnumDescriptor {
	return file_tests_enum_nested_proto_enumTypes[0].Descriptor()
}

func (Outer_Inner) Type() protoreflect.EnumType {
	return &file_tests_enum_nested_proto_enumTypes[0]
}

func (x Outer_Inner) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outer_Inner.Descriptor instead.
func (Outer_Inner) EnumDescriptor() ([]byte, []int) {
	return file_tests_enum_nested_proto_rawDescGZIP(), []int{0, 0}
}

type Outer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Outer) Reset() {
	*x = Outer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_enum_nested_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer) ProtoMessage() {}

func (x *Outer) ProtoReflect() protoreflect.Message {
	mi := &file_tests_enum_nested_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer.ProtoReflect.Descriptor instead.
func (*Outer) Descriptor() ([]byte, []int) {
	return file_tests_enum_nested_proto_rawDescGZIP(), []int{0}
}

var File_tests_enum_nested_proto protoreflect.FileDescriptor

var file_tests_enum_nested_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x6e, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x73,
	0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x22, 0x32, 0x0a, 0x05, 0x4f, 0x75, 0x74, 0x65, 0x72, 0x22, 0x29,
	0x0a, 0x05, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x10, 0x00, 0x12, 0x05, 0x0a, 0x01, 0x41, 0x10, 0x01, 0x12, 0x05, 0x0a, 0x01, 0x42,
	0x10, 0x02, 0x12, 0x05, 0x0a, 0x01, 0x43, 0x10, 0x03, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x70, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x65, 0x6e,
	0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tests_enum_nested_proto_rawDescOnce sync.Once
	file_tests_enum_nested_proto_rawDescData = file_tests_enum_nested_proto_rawDesc
)

func file_tests_enum_nested_proto_rawDescGZIP() []byte {
	file_tests_enum_nested_proto_rawDescOnce.Do(func() {
		file_tests_enum_nested_proto_rawDescData = protoimpl.X.CompressGZIP(file_tests_enum_nested_proto_rawDescData)
	})
	return file_tests_enum_nested_proto_rawDescData
}

var file_tests_enum_nested_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tests_enum_nested_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tests_enum_nested_proto_goTypes = []interface{}{
	(Outer_Inner)(0), // 0: tests.enum.Outer.Inner
	(*Outer)(nil),    // 1: tests.enum.Outer
}
var file_tests_enum_nested_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tests_enum_nested_proto_init() }
func file_tests_enum_nested_proto_init() {
	if File_tests_enum_nested_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tests_enum_nested_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Outer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tests_enum_nested_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_enum_nested_proto_goTypes,
		DependencyIndexes: file_tests_enum_nested_proto_depIdxs,
		EnumInfos:         file_tests_enum_nested_proto_enumTypes,
		MessageInfos:      file_tests_enum_nested_proto_msgTypes,
	}.Build()
	File_tests_enum_nested_proto = out.File
	file_tests_enum_nested_proto_rawDesc = nil
	file_tests_enum_nested_proto_goTypes = nil
	file_tests_enum_nested_proto_depIdxs = nil
}
