// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: tests/message/message_renames.proto

package message

import (
	_ "github.com/alta/protopatch/patch/gopb"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RenamedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RenamedMessage) Reset() {
	*x = RenamedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_message_message_renames_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenamedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenamedMessage) ProtoMessage() {}

func (x *RenamedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tests_message_message_renames_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginalMessage.ProtoReflect.Descriptor instead.
func (*RenamedMessage) Descriptor() ([]byte, []int) {
	return file_tests_message_message_renames_proto_rawDescGZIP(), []int{0}
}

type RenamedOneofMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Contents:
	//	*OriginalOneofMessage_Id
	//	*OriginalOneofMessage_Name
	Contents isRenamedOneofMessage_Contents `protobuf_oneof:"contents"`
}

func (x *RenamedOneofMessage) Reset() {
	*x = RenamedOneofMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_message_message_renames_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenamedOneofMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenamedOneofMessage) ProtoMessage() {}

func (x *RenamedOneofMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tests_message_message_renames_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginalOneofMessage.ProtoReflect.Descriptor instead.
func (*RenamedOneofMessage) Descriptor() ([]byte, []int) {
	return file_tests_message_message_renames_proto_rawDescGZIP(), []int{1}
}

func (m *RenamedOneofMessage) GetContents() isRenamedOneofMessage_Contents {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (x *RenamedOneofMessage) GetId() int32 {
	if x, ok := x.GetContents().(*RenamedOneofMessage_Id); ok {
		return x.Id
	}
	return 0
}

func (x *RenamedOneofMessage) GetName() string {
	if x, ok := x.GetContents().(*RenamedOneofMessage_Name); ok {
		return x.Name
	}
	return ""
}

type isRenamedOneofMessage_Contents interface {
	isRenamedOneofMessage_Contents()
}

type RenamedOneofMessage_Id struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type RenamedOneofMessage_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

func (*RenamedOneofMessage_Id) isRenamedOneofMessage_Contents() {}

func (*RenamedOneofMessage_Name) isRenamedOneofMessage_Contents() {}

type RenamedOuterMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inner *RenamedOuterMessage_InnerMessage `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
}

func (x *RenamedOuterMessage) Reset() {
	*x = RenamedOuterMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_message_message_renames_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenamedOuterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenamedOuterMessage) ProtoMessage() {}

func (x *RenamedOuterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tests_message_message_renames_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginalOuterMessage.ProtoReflect.Descriptor instead.
func (*RenamedOuterMessage) Descriptor() ([]byte, []int) {
	return file_tests_message_message_renames_proto_rawDescGZIP(), []int{2}
}

func (x *RenamedOuterMessage) GetInner() *RenamedOuterMessage_InnerMessage {
	if x != nil {
		return x.Inner
	}
	return nil
}

type OuterMessageWithRenamedInnerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inner *RenamedInnerMessage `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
}

func (x *OuterMessageWithRenamedInnerMessage) Reset() {
	*x = OuterMessageWithRenamedInnerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_message_message_renames_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OuterMessageWithRenamedInnerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OuterMessageWithRenamedInnerMessage) ProtoMessage() {}

func (x *OuterMessageWithRenamedInnerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tests_message_message_renames_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OuterMessageWithRenamedInnerMessage.ProtoReflect.Descriptor instead.
func (*OuterMessageWithRenamedInnerMessage) Descriptor() ([]byte, []int) {
	return file_tests_message_message_renames_proto_rawDescGZIP(), []int{3}
}

func (x *OuterMessageWithRenamedInnerMessage) GetInner() *RenamedInnerMessage {
	if x != nil {
		return x.Inner
	}
	return nil
}

type MessageWithRenamedField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageWithRenamedField) Reset() {
	*x = MessageWithRenamedField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_message_message_renames_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageWithRenamedField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithRenamedField) ProtoMessage() {}

func (x *MessageWithRenamedField) ProtoReflect() protoreflect.Message {
	mi := &file_tests_message_message_renames_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithRenamedField.ProtoReflect.Descriptor instead.
func (*MessageWithRenamedField) Descriptor() ([]byte, []int) {
	return file_tests_message_message_renames_proto_rawDescGZIP(), []int{4}
}

func (x *MessageWithRenamedField) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type RenamedOuterMessage_InnerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RenamedOuterMessage_InnerMessage) Reset() {
	*x = RenamedOuterMessage_InnerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_message_message_renames_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenamedOuterMessage_InnerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenamedOuterMessage_InnerMessage) ProtoMessage() {}

func (x *RenamedOuterMessage_InnerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tests_message_message_renames_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginalOuterMessage_InnerMessage.ProtoReflect.Descriptor instead.
func (*RenamedOuterMessage_InnerMessage) Descriptor() ([]byte, []int) {
	return file_tests_message_message_renames_proto_rawDescGZIP(), []int{2, 0}
}

type RenamedInnerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RenamedInnerMessage) Reset() {
	*x = RenamedInnerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_message_message_renames_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenamedInnerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenamedInnerMessage) ProtoMessage() {}

func (x *RenamedInnerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tests_message_message_renames_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OuterMessageWithRenamedInnerMessage_InnerMessage.ProtoReflect.Descriptor instead.
func (*RenamedInnerMessage) Descriptor() ([]byte, []int) {
	return file_tests_message_message_renames_proto_rawDescGZIP(), []int{3, 0}
}

var File_tests_message_message_renames_proto protoreflect.FileDescriptor

var file_tests_message_message_renames_proto_rawDesc = []byte{
	0x0a, 0x23, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0x0e, 0x70, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x67, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0f, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x3a, 0x14, 0xca, 0xb5, 0x03, 0x10, 0x0a, 0x0e, 0x52,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x65, 0x0a,
	0x14, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x3a, 0x19, 0xca,
	0xb5, 0x03, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x4f, 0x6e, 0x65, 0x6f,
	0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0x89, 0x01, 0x0a, 0x14, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61,
	0x6c, 0x4f, 0x75, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x46, 0x0a,
	0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4f, 0x75, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x1a, 0x0e, 0x0a, 0x0c, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x3a, 0x19, 0xca, 0xb5, 0x03, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0xa7, 0x01, 0x0a, 0x23, 0x4f, 0x75, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x49, 0x6e, 0x6e, 0x65,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x55, 0x0a, 0x05, 0x69, 0x6e, 0x6e, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x49,
	0x6e, 0x6e, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x6e, 0x6e, 0x65,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x1a,
	0x29, 0x0a, 0x0c, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x3a,
	0x19, 0xca, 0xb5, 0x03, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x49, 0x6e,
	0x6e, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x33, 0x0a, 0x17, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x64,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x42, 0x08, 0xca, 0xb5, 0x03, 0x04, 0x0a, 0x02, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64, 0x42,
	0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c,
	0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x70, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x74, 0x65,
	0x73, 0x74, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_tests_message_message_renames_proto_rawDescOnce sync.Once
	file_tests_message_message_renames_proto_rawDescData = file_tests_message_message_renames_proto_rawDesc
)

func file_tests_message_message_renames_proto_rawDescGZIP() []byte {
	file_tests_message_message_renames_proto_rawDescOnce.Do(func() {
		file_tests_message_message_renames_proto_rawDescData = protoimpl.X.CompressGZIP(file_tests_message_message_renames_proto_rawDescData)
	})
	return file_tests_message_message_renames_proto_rawDescData
}

var file_tests_message_message_renames_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tests_message_message_renames_proto_goTypes = []interface{}{
	(*RenamedMessage)(nil),                      // 0: tests.message.OriginalMessage
	(*RenamedOneofMessage)(nil),                 // 1: tests.message.OriginalOneofMessage
	(*RenamedOuterMessage)(nil),                 // 2: tests.message.OriginalOuterMessage
	(*OuterMessageWithRenamedInnerMessage)(nil), // 3: tests.message.OuterMessageWithRenamedInnerMessage
	(*MessageWithRenamedField)(nil),             // 4: tests.message.MessageWithRenamedField
	(*RenamedOuterMessage_InnerMessage)(nil),    // 5: tests.message.OriginalOuterMessage.InnerMessage
	(*RenamedInnerMessage)(nil),                 // 6: tests.message.OuterMessageWithRenamedInnerMessage.InnerMessage
}
var file_tests_message_message_renames_proto_depIdxs = []int32{
	5, // 0: tests.message.OriginalOuterMessage.inner:type_name -> tests.message.OriginalOuterMessage.InnerMessage
	6, // 1: tests.message.OuterMessageWithRenamedInnerMessage.inner:type_name -> tests.message.OuterMessageWithRenamedInnerMessage.InnerMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tests_message_message_renames_proto_init() }
func file_tests_message_message_renames_proto_init() {
	if File_tests_message_message_renames_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tests_message_message_renames_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenamedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_message_message_renames_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenamedOneofMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_message_message_renames_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenamedOuterMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_message_message_renames_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OuterMessageWithRenamedInnerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_message_message_renames_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageWithRenamedField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_message_message_renames_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenamedOuterMessage_InnerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tests_message_message_renames_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenamedInnerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tests_message_message_renames_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*RenamedOneofMessage_Id)(nil),
		(*RenamedOneofMessage_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tests_message_message_renames_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_message_message_renames_proto_goTypes,
		DependencyIndexes: file_tests_message_message_renames_proto_depIdxs,
		MessageInfos:      file_tests_message_message_renames_proto_msgTypes,
	}.Build()
	File_tests_message_message_renames_proto = out.File
	file_tests_message_message_renames_proto_rawDesc = nil
	file_tests_message_message_renames_proto_goTypes = nil
	file_tests_message_message_renames_proto_depIdxs = nil
}
